name: Deploy Docker Container

# Déclenche le workflow sur les pushes à la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier le code depuis le dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Étape 3: Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t mon-site-telechargement .

      # Étape 4: Se connecter à DockerHub (ou ton registre Docker)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 5: Pousser l'image vers DockerHub
      - name: Push Docker image
        run: |
          docker tag mon-site-telechargement username/mon-site-telechargement:latest
          docker push username/mon-site-telechargement:latest

      # Étape 6: Déployer sur Railway (exemple avec Railway CLI)
      - name: Deploy to Railway
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway login --token ${{ secrets.RAILWAY_API_TOKEN }}
          railway deploy --image username/mon-site-telechargement:latest

